hospitals/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView


app_name = "hospital"
urlpatterns = [
    path("", views.HomePageView.as_view(), name="home_page"),
    path("hospital/<int:pk>/", views.HospitalDetail.as_view(), name="h_detail"),
    path("hospital/", views.HospitalList.as_view(), name="h_list"),
    path(
        "hospital_update/<int:pk>/", views.HospitalUpdateView.as_view(), name="h_edit"
    ),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("filter_district/", views.FilterDistrict.as_view(), name="filter_district"),
    path("filter_taluka/", views.FilterTaluka.as_view(), name="filter_taluka"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hospitals.urls'))
]

templates/about.html
{% extends 'base.html' %} {% load static %}
<!--  -->
{% block content %}
<section>
  <div class="container">
    <div id="about">
      <h4>About</h4>
      <dl>
        <dt>What is Covid Hospital Tracker?</dt>
        <dd>
          Covid Hospital Tracker is a crowdsourced initiative to track covid
          hospitals in India.
        </dd>
        <dt>From where the data is taken?</dt>
        <dd>
          The data is taken from
          <a
            href="https://data.gov.in/resources/nin-health-faclities-geo-code-and-additional-parameters-updated-till-last-month"
            target="_blank"
            >data.gov.in</a
          >
        </dd>
        <dt>How do you validate information provided?</dt>
        <dd>
          Currently there are no validations. Any user can update the total
          number of available beds present in a hospital.
        </dd>
      </dl>
    </div>
    <div id="credits">
      <h4>Credits</h4>
      <div>
        Icons made by
        <a href="http://www.freepik.com/" title="Freepik">Freepik</a> from
        <a href="https://www.flaticon.com/" title="Flaticon">flaticon</a> and
        <a href="https://fontawesome.com/">font-awesome</a>.
      </div>
    </div>

    <div id="madeby">
      <h4>Designed and developed by</h4>
      <div>
        <i class="far fa-envelope fa-fw"></i>
        <a href="mailto:sutharlalit.97@gmail.com">Lalit Suthar</a>
        <div id="icons" style="margin-top: 10px;">
          <a
            href="https://twitter.com/lalit_97"
            target="_blank"
            style="margin-right: 10px;"
          >
            <i class="fab fa-twitter fa-fw fa-2x"></i>
          </a>
          <a
            href="https://github.com/lalit97/covid-hospital-tracker"
            target="_blank"
            ><i class="fab fa-github fa-fw fa-2x"></i
          ></a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="Covid Hospital Tracker is a crowdsourced initiative to track covid hospitals in India"
    />
    <meta name="keywords" content="covid, hospital, covid beds" />
    <meta
      property="og:image"
      content="{% static 'img/brand.png' %}"
      width="30"
      height="30"
      alt="hospital bed logo"
    />
    <meta property="og:title" content="Covid Hospital Tracker" />
    <meta
      property="og:description"
      content="description"
      content="Covid Hospital Tracker is a crowdsourced initiative to track covid hospitals in India"
    />
    <title>Covid Hospital Tracker</title>
    <link
      rel="shortcut icon"
      href="{% static 'img/favicon.png' %}"
      alt="hospital bed logo"
    />
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/brands.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/regular.min.css' %}" />

    <link
      href="{% static 'css/style.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    {% block style %} {% endblock style %}

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </head>
  <body>
    <!-- django messages -->
    {% if messages %}
    <div class="alert alert-primary">
      {% for message in messages %}
      <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>
        {{ message }}
      </p>
      {% endfor %}
    </div>
    {% endif %}
    <!-- end messages -->

    <!-- refresh detection algorithm -->
    <form name="refreshForm">
      <input type="hidden" name="visited" value="" />
    </form>
    <!-- end of algorithm -->
    <header>
      <nav
        class="navbar navbar-expand-lg navbar-light"
        style="background-color: #e3f2fd;"
      >
        <a class="navbar-brand" href="#">
          <img
            src="{% static 'img/brand.png' %}"
            width="30"
            height="30"
            class="d-inline-block align-top"
            alt="hospital bed logo"
          />
          Covid Hospital Tracker
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hospital:home_page'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hospital:about'%}">About</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <section>
      <!-- prettier-ignore -->
      {% block content %} 
    {% block filter_district %} 
    {% endblock %} 
    {% block filter_taluka %} 
    {% endblock %} 
    {% endblock %}
    {% block hospital_table %} {% endblock %}
    </section>
    <footer>
      <p>Copyright &copy; Covid Hospital Tracker 2020</p>
    </footer>
  </body>
  <script src="{% static 'js/main.js' %}" type="text/javascript"></script>
</html>