hospitals/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView


app_name = "hospital"
urlpatterns = [
    path("", views.HomePageView.as_view(), name="home_page"),
    path("hospital/<int:pk>/", views.HospitalDetail.as_view(), name="h_detail"),
    path("hospital/", views.HospitalList.as_view(), name="h_list"),
    path(
        "hospital_update/<int:pk>/", views.HospitalUpdateView.as_view(), name="h_edit"
    ),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("filter_district/", views.FilterDistrict.as_view(), name="filter_district"),
    path("filter_taluka/", views.FilterTaluka.as_view(), name="filter_taluka"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hospitals.urls'))
]

hospitals/models.py
from django.db import models


class Hospital(models.Model):
    name = models.CharField(max_length=400, blank=True)
    address = models.CharField(max_length=400, blank=True)
    street = models.CharField(max_length=400, blank=True)
    landmark = models.CharField(max_length=400, blank=True)
    locality = models.CharField(max_length=400, blank=True)
    pincode = models.IntegerField(blank=True, null=True)
    landline = models.CharField(max_length=100, blank=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    altitude = models.FloatField(blank=True, null=True)
    facility_type = models.CharField(max_length=400, blank=True)
    state = models.CharField(max_length=400, blank=True)
    district = models.CharField(max_length=400, blank=True)
    taluka = models.CharField(max_length=400, blank=True)
    block = models.CharField(max_length=400, blank=True)

    def __str__(self):
        return str(self.name)


class Availability(models.Model):
    bed_availabe = models.IntegerField(blank=True, null=True, default=0)
    hospital = models.OneToOneField(Hospital, on_delete=models.CASCADE)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.bed_availabe)


class SearchPincode(models.Model):
    pincode = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.pincode)


class SearchState(models.Model):
    state = models.CharField(max_length=400, blank=True)

    def __str__(self):
        return str(self.state)


class SearchDistrict(models.Model):
    state = models.ForeignKey(SearchState, on_delete=models.CASCADE, null=True)
    district = models.CharField(max_length=400, blank=True)

    def __str__(self):
        return str(self.district)


class SearchTaluka(models.Model):
    state = models.ForeignKey(SearchState, on_delete=models.CASCADE, null=True)
    district = models.ForeignKey(SearchDistrict, on_delete=models.CASCADE, null=True)
    taluka = models.CharField(max_length=400, blank=True)

    def __str__(self):
        return str(self.taluka)

hospitals/forms.py
from django import forms
from .models import Availability


class AvailabilityModelForm(forms.ModelForm):
    class Meta:
        model = Availability
        fields = ["bed_availabe"]
        widgets = {
            "bed_availabe": forms.NumberInput(attrs={"type": "tel", "size": "15"}),
        }

src/hospitals/forms.py
from django import forms
from .models import Availability


class AvailabilityModelForm(forms.ModelForm):
    class Meta:
        model = Availability
        fields = ["bed_availabe"]
        widgets = {
            "bed_availabe": forms.NumberInput(attrs={"type": "tel", "size": "15"}),
        }

    # def __init__(self, *args, **kwargs):
    #     super(AvailabilityModelForm, self).__init__(*args, **kwargs)
    #     self.fields["bed_availabe"] = "Initial value"

hospitals/views.py
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import AvailabilityModelForm
from .models import (
    Hospital,
    Availability,
    SearchState,
    SearchDistrict,
    SearchTaluka,
    SearchPincode,
)


class HomePageView(ListView):
    model = Hospital
    paginate_by = 50
    ordering = ["id"]
    template_name = "hospitals/home_page.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context["states"] = SearchState.objects.all().order_by("state")
        context["districts"] = SearchDistrict.objects.all().order_by("district")
        context["talukas"] = SearchTaluka.objects.all().order_by("taluka")
        return context


class HospitalList(ListView):
    model = Hospital
    paginate_by = 50
    ordering = ["id"]

    def get_queryset(self, **kwargs):
        qs = super(HospitalList, self).get_queryset(**kwargs)

        if self.request.GET.get("state_id"):
            state_id = self.request.GET.get("state_id")
            state = SearchState.objects.get(id=state_id)
            qs = qs.filter(state=state)

        if self.request.GET.get("district_id"):
            district_id = self.request.GET.get("district_id")
            district = SearchDistrict.objects.get(id=district_id)
            qs = qs.filter(district=district)

        if self.request.GET.get("taluka_id"):
            taluka_id = self.request.GET.get("taluka_id")
            taluka = SearchTaluka.objects.get(id=taluka_id)
            qs = qs.filter(taluka=taluka)

        return qs


class FilterDistrict(TemplateView):
    template_name = "hospitals/filter_district.html"

    def get_context_data(self, **kwargs):
        context = super(FilterDistrict, self).get_context_data(**kwargs)
        if self.request.GET.get("state_id"):
            state_id = self.request.GET.get("state_id")
            state = SearchState.objects.get(id=state_id)
            districts = SearchDistrict.objects.filter(state=state).order_by("district")
        else:
            districts = SearchDistrict.objects.all().order_by("district")
        context["districts"] = districts
        return context


class FilterTaluka(TemplateView):
    template_name = "hospitals/filter_taluka.html"

    def get_context_data(self, **kwargs):
        context = super(FilterTaluka, self).get_context_data(**kwargs)
        if self.request.GET.get("district_id"):
            district_id = self.request.GET.get("district_id")
            district = SearchDistrict.objects.get(id=district_id)
            talukas = SearchTaluka.objects.filter(district=district).order_by("taluka")
        else:
            talukas = SearchTaluka.objects.all().order_by("taluka")
        context["talukas"] = talukas
        return context


class HospitalDetail(DetailView):
    model = Hospital


class HospitalUpdateView(SuccessMessageMixin, UpdateView):
    model = Availability
    template_name = "hospitals/hospital_update.html"
    form_class = AvailabilityModelForm
    success_url = reverse_lazy("hospital:home_page")
    success_message = "Beds Updated Successfully. Thank you for the contribution."

    def get_context_data(self, **kwargs):
        context = super(HospitalUpdateView, self).get_context_data(**kwargs)
        hospital_id = self.kwargs.get("pk")
        context["hospital_id"] = hospital_id
        return context

    def get_object(self):
        id_ = self.kwargs.get("pk")
        hospital = Hospital.objects.get(id=id_)
        try:
            avail_obj = hospital.availability
        except Availability.DoesNotExist:
            avail_obj = Availability.objects.create(hospital=hospital)
        return avail_obj

src/hospitals/views.py
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView
from .forms import AvailabilityModelForm
from .models import (
    Hospital,
    Availability,
    SearchState,
    SearchDistrict,
    SearchTaluka,
    SearchPincode,
)


class HomePageView(ListView):
    model = Hospital
    paginate_by = 50
    template_name = "hospitals/home_page.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context["states"] = SearchState.objects.all().order_by("state")
        context["districts"] = SearchDistrict.objects.all().order_by("district")
        context["talukas"] = SearchTaluka.objects.all().order_by("taluka")
        return context


class HospitalList(ListView):
    model = Hospital
    paginate_by = 60

    def get_queryset(self, **kwargs):
        qs = super(HospitalList, self).get_queryset(**kwargs)

        if self.request.GET.get("state_id"):
            state_id = self.request.GET.get("state_id")
            state = SearchState.objects.get(id=state_id)
            qs = qs.filter(state=state)

        if self.request.GET.get("district_id"):
            district_id = self.request.GET.get("district_id")
            district = SearchDistrict.objects.get(id=district_id)
            qs = qs.filter(district=district)

        if self.request.GET.get("taluka_id"):
            taluka_id = self.request.GET.get("taluka_id")
            taluka = SearchTaluka.objects.get(id=taluka_id)
            qs = qs.filter(taluka=taluka)

        return qs


class FilterDistrict(TemplateView):
    template_name = "hospitals/filter_district.html"

    def get_context_data(self, **kwargs):
        context = super(FilterDistrict, self).get_context_data(**kwargs)
        if self.request.GET.get("state_id"):
            state_id = self.request.GET.get("state_id")
            state = SearchState.objects.get(id=state_id)
            districts = SearchDistrict.objects.filter(state=state).order_by("district")
        else:
            districts = SearchDistrict.objects.all().order_by("district")
        context["districts"] = districts
        return context


class FilterTaluka(TemplateView):
    template_name = "hospitals/filter_taluka.html"

    def get_context_data(self, **kwargs):
        context = super(FilterTaluka, self).get_context_data(**kwargs)
        if self.request.GET.get("district_id"):
            district_id = self.request.GET.get("district_id")
            district = SearchDistrict.objects.get(id=district_id)
            talukas = SearchTaluka.objects.filter(district=district).order_by("taluka")
        else:
            talukas = SearchTaluka.objects.all().order_by("taluka")
        context["talukas"] = talukas
        return context


class HospitalDetail(DetailView):
    model = Hospital


class HospitalUpdateView(UpdateView):
    model = Availability
    template_name = "hospitals/hospital_update.html"
    form_class = AvailabilityModelForm
    success_url = reverse_lazy("hospital:home_page")

    def get_context_data(self, **kwargs):
        context = super(HospitalUpdateView, self).get_context_data(**kwargs)
        hospital_id = self.kwargs.get("pk")
        context["hospital_id"] = hospital_id
        return context

    def get_object(self):
        id_ = self.kwargs.get("pk")
        hospital = Hospital.objects.get(id=id_)
        try:
            avail_obj = hospital.availability
        except Availability.DoesNotExist:
            avail_obj = Availability.objects.create(hospital=hospital)
        return avail_obj

hospitals/templates/hospitals/filter_district.html
<!-- {% load static %} -->
{% for district in districts %}

<a
  class="dropdown-item dropdown-district"
  id="district-{{district.id}}"
  data-district-id="{{district.id}}"
  url="{% url 'hospital:h_list' %}"
  taluka-url="{% url 'hospital:filter_taluka' %}"
  >{{district}}</a
>
{% endfor %}

<!-- <script src="{% static 'js/main.js' %}" type="text/javascript"></script> -->

hospitals/templates/hospitals/filter_taluka.html
<!-- {% load static %} -->
{% for taluka in talukas %}
<a
  class="dropdown-item dropdown-taluka"
  id="taluka-{{taluka.id}}"
  data-taluka-id="{{taluka.id}}"
  url="{% url 'hospital:h_list' %}"
  >{{taluka}}</a
>
{% endfor %}

<!-- <script src="{% static 'js/main.js' %}" type="text/javascript"></script> -->

hospitals/templates/hospitals/home_page.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block content %}
<div id="home-page">
  <div class="dropdown row" id="mydropdown">
    <div class="btn-group col-xs-12 col-sm-4">
      <button
        class="btn btn-primary dropdown-toggle"
        type="button"
        id="b_state"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        Select State
      </button>
      <div class="dropdown-menu" id="s_state" aria-labelledby="b_state">
        {% for state in states %}
        <a
          class="dropdown-item dropdown-state"
          id="state-{{state.id}}"
          data-state-id="{{state.id}}"
          url="{% url 'hospital:h_list' %}"
          district-url="{% url 'hospital:filter_district' %}"
          >{{state}}</a
        >
        {% endfor %}
      </div>
    </div>
    <div class="btn-group col-xs-12 col-sm-4">
      <button
        class="btn btn-primary dropdown-toggle"
        type="button"
        id="b_district"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        Select District
      </button>
      {% block filter_district %}
      <div
        class="dropdown-menu"
        id="s_district"
        aria-labelledby="b_district"
      ></div>
      {% endblock %}
    </div>
    <div class="btn-group col-xs-12 col-sm-4">
      <button
        class="btn btn-primary dropdown-toggle"
        type="button"
        id="b_taluka"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        Select Taluka
      </button>
      {% block filter_taluka %}
      <div class="dropdown-menu" id="s_taluka" aria-labelledby="b_taluka"></div>
      {% endblock %}
    </div>
  </div>
</div>
{% endblock %}
<!--  -->
{% block hospital_table %}
<div id="hospital_table" class="table-responsive">
  <table class="table table-hover table-bordered">
    <thead style="background-color: #e3f2fd;">
      <tr>
        <th scope="col">SN</th>
        <th scope="col">Name</th>
        <th scope="col">Beds Available</th>
        <th scope="col">Updated On</th>
        <th scope="col">Address</th>
      </tr>
    </thead>
    <tbody>
      {% for hospital in page_obj %}
      <tr>
        <th scope="row">
          {{forloop.counter|add:page_obj.start_index|add:-1}}
        </th>
        <td>
          <a href="{%url 'hospital:h_detail' pk=hospital.pk %}">
            {{hospital.name}}
          </a>
        </td>
        <td>
          <div class="beds-parent" id="hospital-{{hospital.id}}">
            <div class="beds-child1">
              <span>
                {% if hospital.availability.bed_availabe == 0 %}
                <p>unknown</p>
                {% elif hospital.availability.bed_availabe == "" %}
                <p>unknown</p>
                {% else %} {{hospital.availability.bed_availabe}} {% endif %}
              </span>
            </div>
            <div class="beds-child2">
              <button
                type="button"
                id="{{hospital.id}}"
                class="btn btn-primary editbtn"
                edit-url="{% url 'hospital:h_edit' hospital.id%}"
              >
                <i class="far fa-edit editicon"></i>
              </button>
            </div>
          </div>
        </td>
        <td>
          {% if hospital.availability.last_updated != "" %}
          {{hospital.availability.last_updated}} {% else %}
          <p>NA</p>
          {% endif %}
        </td>

        <td>{{hospital.address}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div>
    <ul class="pagination justify-content-center">
      <li class="page-item">
        {% if page_obj.has_previous %}
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
          >previous</a
        >
        {% endif %}
      </li>
      <li class="page-item">
        <a class="page-link">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </a>
      </li>
      <li class="page-item">
        {% if page_obj.has_next %}
        <a class="page-link" href="?page={{ page_obj.next_page_number }}"
          >next</a
        >
        {% endif %}
      </li>
    </ul>
  </div>
</div>
{% endblock %}

hospitals/templates/hospitals/hospital_detail.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block style %}
<style>
  tr td {
    background-color: #343a40;
    color: #fff;
  }
  tr td + td {
    background-color: #fff;
    color: #000;
  }
</style>
{% endblock %}

<!--  -->
{% block content %}
<table class="table table-hover table-bordered text-center">
  <tbody>
    <tr>
      <td>Name</td>
      <td>{{object.name}}</td>
    </tr>
    <tr>
      <td>Address</td>
      <td>{{object.address}}</td>
    </tr>
    <tr>
      <td>Street</td>
      <td>{{object.street}}</td>
    </tr>
    <tr>
      <td>Landmark</td>
      <td>{{object.landmark}}</td>
    </tr>
    <tr>
      <td>Locality</td>
      <td>{{object.locality}}</td>
    </tr>
    <tr>
      <td>PinCode</td>
      <td>{{object.pinCode}}</td>
    </tr>
    <tr>
      <td>Contact</td>
      <td>{{object.landline}}</td>
    </tr>
    <tr>
      <td>Type</td>
      <td>{{object.facility_type}}</td>
    </tr>
    <tr>
      <td>State</td>
      <td>{{object.state}}</td>
    </tr>
    <tr>
      <td>District</td>
      <td>{{object.district}}</td>
    </tr>
    <tr>
      <td>Taluka</td>
      <td>{{object.taluka}}</td>
    </tr>
    <tr>
      <td>Block</td>
      <td>{{object.block}}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

hospitals/templates/hospitals/hospital_list.html
<table class="table table-hover table-bordered">
  <thead style="background-color: #e3f2fd;">
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Name</th>
      <th scope="col">Beds Available</th>
      <th scope="col">Updated On</th>
      <th scope="col">Address</th>
    </tr>
  </thead>
  <tbody>
    {% for hospital in page_obj %}
    <tr>
      <th scope="row">{{forloop.counter|add:page_obj.start_index|add:-1}}</th>
      <td>
        <a href="{%url 'hospital:h_detail' pk=hospital.pk %}">
          {{hospital.name}}
        </a>
      </td>
      <td>
        <div class="beds-parent" id="hospital-{{hospital.id}}">
          <div class="beds-child1">
            <span>
              {% if hospital.availability.bed_availabe == 0 %}
              <p>unknown</p>
              {% elif hospital.availability.bed_availabe == "" %}
              <p>unknown</p>
              {% else %} {{hospital.availability.bed_availabe}} {% endif %}
            </span>
          </div>
          <div class="beds-child2">
            <button
              type="button"
              id="{{hospital.id}}"
              class="btn btn-primary editbtn"
              edit-url="{% url 'hospital:h_edit' hospital.id%}"
            >
              <i class="far fa-edit editicon"></i>
            </button>
          </div>
        </div>
      </td>
      <td>
        {% if hospital.availability.last_updated != "" %}
        {{hospital.availability.last_updated}} {% else %}
        <p>NA</p>
        {% endif %}
      </td>

      <td>{{hospital.address}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div>
  <ul class="pagination justify-content-center">
    <li class="page-item">
      {% if page_obj.has_previous %}
      <a
        class="page-link"
        id="list_prev"
        page="{{ page_obj.previous_page_number }}"
        style="color: blue;"
        >previous</a
      >
      {% endif %}
    </li>
    <li class="page-item">
      <a class="page-link">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </a>
    </li>
    <li class="page-item">
      {% if page_obj.has_next %}
      <a
        class="page-link"
        id="list_next"
        style="color: blue;"
        page="{{ page_obj.next_page_number }}"
        >next</a
      >
      {% endif %}
    </li>
  </ul>
</div>

hospitals/templates/hospitals/hospital_update.html
<form method="post" action="{% url 'hospital:h_edit' hospital_id %}">
  {% csrf_token %}
  <div style="margin: auto;">
    <div style="float: left; margin-bottom: 2px;">
      {{ form }}
    </div>
    <div style="float: right;">
      <button type="submit" value="Update" class="btn btn-primary">
        <i class="far fa-check-square"></i>
      </button>
    </div>
  </div>
</form>

<!-- 
  This does not works
<button
  type="button"
  data-id="{{hospital_id}}"
  class="btn btn-success"
  id="updatebtn"
>
  <i class="fas fa-check"></i>
</button> 

option 2
  we will need these attributes later for 
  verifying data on basis of location
  id=updatebtn 
  data-id="{{hospital_id}}"

-->